In [82]:
import numpy as np
import pandas as pd

df = pd.read_csv('dota2Train.csv')

df2 = pd.read_csv('dota2Test.csv')
print(df)
print(df2)
n=2000

       -1  223  2  2.1  0  0.1  ...  0.97  0.98  0.99  0.100  0.101  0.102
0       1  152  2    2  0    0  ...     0     0     0      0      0      0
1       1  131  2    2  0    0  ...     0     0     0      0      0      0
2       1  154  2    2  0    0  ...     0     0     0      0      0      0
3      -1  171  2    3  0    0  ...     0     0     0      0      0      0
4       1  122  2    3  0    1  ...     0     0     0      0      0     -1
...    ..  ... ..  ... ..  ...  ...   ...   ...   ...    ...    ...    ...
92644  -1  154  2    3  1    0  ...     0     0     0      0      0      0
92645   1  154  2    2  0    0  ...     0     0     0      0      0      0
92646   1  111  2    3  0    0  ...     0     0     0      0      0      0
92647  -1  185  2    2  0    0  ...     0     0     0      0      0      0
92648  -1  204  2    2  0   -1  ...     0     0     0      0      0      0

[92649 rows x 117 columns]
       -1  223  8  2  0  -1.1  0.1  ...  0.96  0.97  0.98  0.99  0.100  

In [0]:
#train資料的前處理


z1=np.ones(n,dtype=np.float)
z2=np.ones(n,dtype=np.float)
zz1=np.zeros((5,n),dtype=np.int)
zz2=np.zeros((5,n),dtype=np.int)
for i in range(n):
  a=0
  b=0
  for j in range(4,117):
    if df.loc[i][j] ==1:
      z1[i]=z1[i]*(j/10)
      zz1[a][i]=j
      a=a+1
    if df.loc[i][j] ==-1:
      z2[i]=z2[i]*(j/10)
      zz2[b][i]=j
      b=b+1


In [0]:

z3=np.ones(n,dtype=np.float)
z4=np.ones(n,dtype=np.float)
zz3=np.zeros((5,n),dtype=np.int)
zz4=np.zeros((5,n),dtype=np.int)
for i in range(n):
  a=0
  b=0
  for j in range(4,117):
    if df2.loc[i][j] ==1:
      z3[i]=z3[i]*(j/10)
      zz3[a][i]=j
      a=a+1
    if df2.loc[i][j] ==-1:
      z4[i]=z4[i]*(j/10)
      zz4[b][i]=j
      b=b+1


In [0]:
z=np.zeros(n,dtype=np.int)
for i in range(n):
  if df.loc[i][0]==-1:
    z[i]=1

train_y=pd.DataFrame({'v':z})

z=np.zeros(n,dtype=np.int)
for i in range(n):
  if df2.loc[i][0]==-1:
    z[i]=1

test_y=pd.DataFrame({'v':z})

In [86]:
train_x=pd.DataFrame({
    '1T':z1,
    '-1T':z2,
    })

test_x=pd.DataFrame({
    '1T':z3,
    '-1T':z4,
    })
print(zz1)

[[  7   7  20 ...  12  20  20]
 [ 17  25  38 ...  17  25  29]
 [ 29  28  57 ...  25  32  47]
 [ 30  35  65 ...  51  59  77]
 [ 74  62  98 ...  76 109 107]]


In [87]:
train_x1=pd.DataFrame({
    '0':zz1[0],
    '1':zz1[1],
    '2':zz1[2],
    '3':zz1[3],
    '4':zz1[4],
    '5':zz2[0],
    '6':zz2[1],
    '7':zz2[2],
    '8':zz2[3],
    '9':zz2[4]
    })

test_x1=pd.DataFrame({
    '0':zz3[0],
    '1':zz3[1],
    '2':zz3[2],
    '3':zz3[3],
    '4':zz3[4],
    '5':zz4[0],
    '6':zz4[1],
    '7':zz4[2],
    '8':zz4[3],
    '9':zz4[4]
    })
print(train_x1)

       0   1   2   3    4   5   6   7   8    9
0      7  17  29  30   74   9  24  38  96  101
1      7  25  28  35   62   9  23  49  75   96
2     20  38  57  65   98  10  26  45  50  107
3     19  34  39  47   76   9  12  14  32   89
4      5  60  66  77  107  15  31  58  73  116
...   ..  ..  ..  ..  ...  ..  ..  ..  ..  ...
1995   5   9  20  22   96  37  47  68  73   78
1996  16  42  57  62  101  11  21  47  74   96
1997  12  17  25  51   76  14  32  35  47   89
1998  20  25  32  59  109  15  39  50  80  101
1999  20  29  47  77  107  12  15  17  53   96

[2000 rows x 10 columns]


In [0]:
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression

In [93]:
clf = MLPClassifier(hidden_layer_sizes=(8,4),learning_rate_init=0.001,random_state=1, max_iter=1000).fit(train_x1, train_y)
prey=clf.predict(test_x1)
acc = accuracy_score(test_y, prey)
print(acc)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.519


In [89]:
clf = MLPClassifier(hidden_layer_sizes=(8,4),learning_rate_init=0.001,random_state=1, max_iter=1000).fit(train_x, train_y)
prey=clf.predict(test_x)
acc = accuracy_score(test_y, prey)
print(acc)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.5375
